"""
FILE PURPOSE: Flask-Mail wrapper (TDR §8.1). P1 scope is the password-
reset notification ONLY — the Contact/Request-a-Project notification
functions this file will eventually also hold are P4 scope (Master
Project Blueprint §1: "Flask-Mail wrapper for contact/request/
password-reset notifications" — this milestone builds one of the three).

PROMPT FOR LLM IMPLEMENTATION:
1. Import Message from flask_mail, mail from app.extensions,
   current_app, url_for, and Python's logging module
   (logger = logging.getLogger(__name__)).
2. def send_password_reset_email(admin_user, token): build a Message
   with subject "Password Reset Requested" (matches the Notification
   Templates table, PDR §14.2 / TDR appendix), recipients=
   [current_app.config["ADMIN_NOTIFICATION_EMAIL"]], sender=
   current_app.config["MAIL_DEFAULT_SENDER"], and a plain-text body
   containing the signed, time-limited reset link built via
   url_for("auth.reset_password", token=token, _external=True) (PDR
   §14.2: "Signed, time-limited reset link" is the entire content).
3. Call mail.send(msg) inside a try/except; on success log at INFO
   ("Password reset email sent for admin_user=%s", admin_user.username);
   on any exception, log at ERROR with the traceback (logger.exception)
   but do NOT re-raise — per TDR §2/§12, a failed notification email
   must never block or roll back the calling flow (here: the token was
   already generated by auth.py regardless of mail success).
4. Do not add send_contact_notification / send_project_request_notification
   here yet — leave a one-line comment noting they land in P4 alongside
   the Contact/Request-a-Project routes, so this file's shape doesn't
   need to change later, just grow.

DEBUGGING:
# print(f"[DEBUG] mailer.send_password_reset_email — sending to {current_app.config.get('ADMIN_NOTIFICATION_EMAIL')!r}")

OFFLINE DOCKER TEST CASES:
- With MAIL_SUPPRESS_SEND=True (the Docker test config), calling
  send_password_reset_email(admin, "faketoken") does not raise and does
  not attempt any real network I/O.
- The composed Message's subject is exactly "Password Reset Requested"
  and its body contains the token string somewhere within the rendered
  reset URL.
- If mail.send() is monkeypatched to raise, the function still returns
  normally (no unhandled exception propagates to the caller).
"""
